kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these labels belongs to deplyment resource
  labels:
    project: expense
    component: backend
    environment: dev
    tier: app
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      project: expense
      component: backend
      environment: dev
      tier: app
    # below is the pod defination
  template:
    metadata:
      labels:
        project: expense
        component: backend
        environment: dev
        tier: app
    spec:
      containers:
      - name: backend
        image: charan466/backend:1.0.0
        env:
            - name: backend_ROOT_PASSWORD
              value: ExpenseApp@1
        envFrom:
        - configMapRef:
            name: backend

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    component: backend
    environment: dev
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port