apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None # This is called headless service
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
      matchLabels:
        component: mysql
        project: expense
        tier: db
  serviceName: "mysql-headless" # you must create this Headless Service
  replicas: 2
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: charan466/mysql:v1.0.0
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ExpenseApp@1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1f
  # PVC declaration, it is mandatory
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: expense-ebs
      resources:
        requests:
          storage: 2Gi
