# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mysql
#   namespace: expense
# spec:
#   storageClassName: "expense-ebs" # Empty string must be explicitly set otherwise default StorageClass will be set
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 18Gi

# ---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  serviceName: "mysql" # you must create this Headless Service
  replicas: 3
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: charan466/mysql:v1.0.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ExpenseApp@1
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      nodeSelector:
        topology.kubernetes.io/zone: us-east-1f
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: expense-ebs
      resources:
        requests:
          storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  clusterIP: None # This is called headless service
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port