apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "expense-ebs" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels: # has to match .spec.template.metadata.labels
      project: expense
      component: mysql
      environment: dev
      tier: db
  serviceName: "mysql-1"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:  # has to match .spec.selector.matchLabels
        project: expense
        component: mysql
        environment: dev
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: charan466/mysql:1.0.0
        ports:
        - containerPort: 3306
          name: mysql-2
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql